"""initial_schema

Revision ID: e258e7a8ea74
Revises: 
Create Date: 2026-04-12 02:02:59.406632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e258e7a8ea74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('platforms', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Enum('help_seeking', 'complaint', 'comparison', 'technical', 'enterprise', name='leadintent'), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='leadpriority'), nullable=False),
    sa.Column('suggested_reply', sa.Text(), nullable=False),
    sa.Column('edited_reply', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'published', 'dismissed', name='leadstatus'), nullable=False),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    op.drop_table('keywords')
    # ### end Alembic commands ###
